FluxoCaixa.Web/Models/ErrorViewModel.cs
using System;

namespace FluxoCaixa.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FluxoCaixa.Web/Controllers/BalancoController.cs
using FluxoCaixa.ClientServices.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FluxoCaixa.Web.Controllers
{
    public class BalancoController : Controller
    {
        private readonly IBalancoClientService _balancoClientService;
       
        public BalancoController(IBalancoClientService balancoClientService)
        {
            _balancoClientService = balancoClientService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var balancoMensalLista = _balancoClientService.GetBalancoMensal(null, null);
            return View(balancoMensalLista);
        }

        [HttpPost]
        public IActionResult Index(bool gerarBalancoDiario = true)
        {
            _balancoClientService.GerarBalancoDiario();

            return RedirectToAction("Index");
        }
    }


}

FluxoCaixa.Web/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FluxoCaixa.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace FluxoCaixa.Web.Controllers
{
    public class ErrorController : Controller
    {
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FluxoCaixa.Web/Controllers/FluxoCaixaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FluxoCaixa.Web.Models;
using System.Net;
using System.Net.Http;

namespace FluxoCaixa.Web.Controllers
{
    public class FluxoCaixaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }      
    }
}

FluxoCaixa.Web/Controllers/LancamentoController.cs
using AutoMapper;
using FluxoCaixa.ClientServices.Interfaces;
using FluxoCaixa.Common.Models;
using FluxoCaixa.Common.Models.ViewModel;
using FluxoCaixa.Dominio.Entidades;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FluxoCaixa.Web.Controllers
{
    public class LancamentoController : Controller
    {
        private readonly ILancamentoFinanceiroClientServices _lancamentoFinanceiroClientServices;
        private readonly IMapper _mapper;

        public LancamentoController(ILancamentoFinanceiroClientServices lancamentoFinanceiroClientServices, IMapper mapper)
        {
            _lancamentoFinanceiroClientServices = lancamentoFinanceiroClientServices;
            _mapper = mapper;
        }

        public IActionResult Index(DateTime? data, int? tipoLancamento, bool? consolidado)
        {
            try
            {
                var model = new LancamentoFinanceiroFiltroViewModel();

                var listaLancamentos = _lancamentoFinanceiroClientServices.FiltrarLancamentosFinanceiro(new LancamentoFinanceiroFiltro() { DataLancamento = data, TipoLancamento = tipoLancamento, Consolidado = consolidado });
                model.ListaLancamentoFinanceiro = _mapper.Map<List<LancamentoFinanceiroModel>, List<LancamentoFinanceiroViewModel>>(listaLancamentos.ToList());

                return View(model);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            var model = new LancamentoFinanceiroInserirViewModel();

            return View(model);
        }

        [HttpPost]
        public IActionResult Cadastrar(LancamentoFinanceiroInserirViewModel model)
        {
            try
            {
                _lancamentoFinanceiroClientServices.InserirLancamentoFinaneiro(_mapper.Map<LancamentoFinanceiroInserirViewModel, LancamentoFinanceiroApiModel>(model));

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw;
            }
        }

        public JsonResult Excluir(int id)
        {
            try
            {
                _lancamentoFinanceiroClientServices.ExcluirLancamentoFinanceiro(id);
            }
            catch (Exception ex)
            {
                return Json(new { erro = true, mensagem = $"Ocorre um erro ao excluir lançamento {ex.Message}" });
            }
            return Json(new { erro = false, mensagem = "Lançamento excluído com sucesso" });
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            try
            {
                var model = _mapper.Map<LancamentoFinanceiroModel, LancamentoFinanceiroInserirViewModel>(_lancamentoFinanceiroClientServices.GetLancamentoFinanceiro(id));

                return View(model);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult Editar(LancamentoFinanceiroInserirViewModel model)
        {
            try
            {
                _lancamentoFinanceiroClientServices.AtualizarLancamentoFinanceiro(_mapper.Map<LancamentoFinanceiroInserirViewModel, LancamentoFinanceiroApiUpdateModel>(model));

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

FluxoCaixa.Web/Views/Balanco/Index.cshtml
@model List<FluxoCaixa.Common.Models.BalancoMensalModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Index", "Balanco", FormMethod.Post))
{
    <div class="row">
        <h3>Gerar balanço diário</h3>
        <div>
            <input type="submit" name="Gerar balanço diário" class="btn btn-default" value="Gerar" />
        </div>
    </div>
    <div class="row">
        <h3>Balanço mensal</h3>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Ano</th>
                    <th scope="col">Mês</th>
                    <th scope="col">Crédito</th>
                    <th scope="col">Débito</th>
                    <th scope="col">Saldo</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var balanco in Model)
                {

                    <tr>
                        <td scope="row">@balanco.Ano</td>
                        <td scope="row">@balanco.DescricaoMes</td>
                        <td scope="row">@balanco.SomaCredito.ToString("N2")</td>
                        <td scope="row">@balanco.SomaDebito.ToString("N2")</td>
                        <td scope="row">@balanco.SomaSaldo.ToString("N2")</td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

}

FluxoCaixa.Web/Views/FluxoCaixa/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h2> Bem vindo ao gestão de fluxo de caixa clique em lançamentos para cadastrar, atualizar, excluir ou visualizar um lançamento ou clique em balanços para visualizar os balanço mensais ou iniciar um balanço diário</h2>
</div>

FluxoCaixa.Web/Views/Lancamento/Cadastrar.cshtml
@model FluxoCaixa.Common.Models.ViewModel.LancamentoFinanceiroInserirViewModel
@{
    ViewData["Title"] = "Cadastrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Cadastrar", "Lancamento", FormMethod.Post))
{
    <h2>Cadastrar</h2>

    <div class="row">
        <div class="form-group">
            <label for="Valor">Valor</label>
            @Html.TextBoxFor(_ => _.Valor)
        </div>
        <div class="form-group">
            <label for="TipoLancamento">Tipo Lançamento</label>
            @Html.RadioButtonFor(model => model.TipoLancamento, true) Crédito
            @Html.RadioButtonFor(model => model.TipoLancamento, false) Débito
        </div>
        <div class="form-group">
            <input type="submit" value="Salvar" class="btn btn-primary" />
        </div>
    </div>
}

FluxoCaixa.Web/Views/Lancamento/Editar.cshtml
@model FluxoCaixa.Common.Models.ViewModel.LancamentoFinanceiroInserirViewModel
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Editar", "Lancamento", FormMethod.Post))
{
    <h2>Editar</h2>

    <div class="row">
        <div class="form-group">
            <label for="Valor">Valor</label>
            @Html.TextBoxFor(_ => _.Valor)
        </div>
        <div class="form-group">
            <label for="TipoLancamento">Tipo Lançamento</label>
            @Html.RadioButtonFor(_ => _.TipoLancamento, true) Crédito
            @Html.RadioButtonFor(_ => _.TipoLancamento, false) Débito
        </div>
        <div class="form-group">
            <input type="submit" value="Salvar" class="btn btn-primary" />
        </div>
    </div>
}

FluxoCaixa.Web/Views/Lancamento/Index.cshtml
@model FluxoCaixa.Common.Models.ViewModel.LancamentoFinanceiroFiltroViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <h3>Lançamentos</h3>
    <div>
        <a asp-action="Cadastrar" asp-controller="Lancamento" class="btn btn-default">Cadastrar</a>
    </div>
</div>
<div class="row">
    @if (Model.ListaLancamentoFinanceiro.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th scope="col">Data Lançamento</th>
                    <th scope="col">Valor</th>
                    <th scope="col">Tipo Lançamento</th>
                    <th scope="col">Consolidado?</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var lancamento in Model.ListaLancamentoFinanceiro)
                {
                    <tr>
                        <td scope="row">@Html.ActionLink("Editar", "Editar", "Lancamento", new { id = lancamento.Id })</td>
                        <td scope="row"><a href="#" onclick="ExcluirLancamento('@lancamento.Id')">Excluir</a></td>
                        <td scope="row">@lancamento.DataHoraLancamento</td>
                        <td scope="row">@lancamento.Valor</td>
                        <td scope="row">@lancamento.TipoLancamento</td>
                        <td scope="row">@lancamento.Consolidado</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

@section Scripts {

    <script type="text/javascript">

        function ExcluirLancamento(idLancamento) {

            $.ajax({
                url: "Lancamento/Excluir",
                data: { id: idLancamento },
                cache: false,
                type: "POST",
                success: function (data) {
                    alert(data.mensagem);

                    window.location.href = "Lancamento";

                }, error: function (error) {

                }
            });
        }

    </script>
}

FluxoCaixa.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fluxo Caixa</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <p class="navbar-brand">FluxoCaixa Web</p>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Lancamento" asp-action="Index">Lançamentos</a></li>
                    <li><a asp-area="" asp-controller="Balanco" asp-action="Index">Balanços</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - FluxoCaixa Web</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>